---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: k8snginxappsot
  namespace: fluxcd-play
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/ssabag4/k8s_nginxapp_sot.git

